server:
  port: 8500

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

file:
  upload-dir: /home/site/wwwroot/uploads

#file:
#  upload-dir: C:/Users/Justin/Projects/uploads/