spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/librarydb?serverTimezone=UTC
    username: root
    password: ""


logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

